GET http://localhost:3003/api/subscribers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2FtYWwgT2poYSIsImlhdCI6MTYwNTg1ODkyNSwiZXhwIjoxNjA1ODU4OTg1fQ.R68xvCALL1e2jEQTqw8phq1di8DuYmNW5_XBbG-b8sM


###

POST http://localhost:3003/api/subscribers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2FtYWwgT2poYSIsImlhdCI6MTYwNTg1ODkyNSwiZXhwIjoxNjA1ODU4OTg1fQ.R68xvCALL1e2jEQTqw8phq1di8DuYmNW5_XBbG-b8sM
Content-Type: application/json

{
    "name": "Kamal Ojha",
    "subscribedToChannel": "Kiran Ojha"
    
}

###
DELETE http://localhost:3003/api/subscribers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lyYW4gT2poYSIsImlhdCI6MTYwNTg1MTgwOX0.1IXZM6lfULvF2Idk0ptaDj5WcEydT6tYBZ-5rfi8xAI



###
GET http://localhost:3003/api/subscribers/5fb4f1ecf1acfd2dcc3d53e3


###
PATCH http://localhost:3003/api/subscribers/5fb4f2eda38d563420989437
Content-Type: application/json

{
    "name": "Kamal Ojha",
    "subscribedToChannel": "Kamal Ojha"
    
}


###
DELETE http://localhost:3003/api/subscribers/5fb4e170252f57335c6eeb67

###

GET http://localhost:3003/api/users/register

###
GET http://localhost:3003/api/users/login

###
GET http://localhost:3003/api/users/kiran


###
POST http://localhost:3003/api/users/register
Content-Type: application/json

{
    "name": " Kamal Ojha",
    "password": "password"
}

###
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "name": "Kamal Ojha",
    "password": "password"
}

###

POST http://localhost:4000/api/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2FtYWwgT2poYSIsImlhdCI6MTYwNTg2NjU0M30.Eal8VZ34Afrar8ZGmNCnC4rx1QnVcpf5JGSKkzqI2tA"
}